version: '3.4'

services:
  moviedb:
    container_name: moviedb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - moviedb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*


  movie.api:
    container_name: movie.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=moviedb,1433;Database=MoviesDb; User=sa; Password=Password12*"
    ports:
      - "5001:80"
    depends_on:
      - moviedb