version: '3.4'

services:
  moviedb:
    container_name: moviedb
    environment:
        SA_PASSWORD: "A!VeryComplex123Password"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - moviedb_volume:/var/opt/mssql
       

  movie.api:
    container_name: movie.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=moviedb,1433;Database=MoviesDB;User=sa;Password=A!VeryComplex123Password;MultipleActiveResultSets=true,TrustServerCertificate=true"
    depends_on:
      - moviedb
    ports:
      - "5001:80"