version: '3.4'

services:
  moviedb:
    container_name: moviedb
    environment:
        SA_PASSWORD: "admin12345"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - moviedb_volume:/var/opt/mssql
    
    

  movie.api:
    container_name: movie.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=moviedb;Database=MoviesDB;User=sa;Password=admin12345;"
    depends_on:
      - moviedb
    ports:
      - "5001:80"